config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  devise_for :users
  root to: "homes#top"
  get "home/about"=>"homes#about"
  resources :books, only: [:index,:show,:edit,:create,:destroy,:update]do
     resource :favorites, only: [:create,:destroy]
     resources :book_comments, only: [:create,:destroy]
  end
   get 'searchs/about', to: "searchs#top",as: "search"
  resources :users, only: [:index,:show,:edit,:update]do
     resource :relationships, only: [:create, :destroy]
    get 'followings' => 'relationships#followings', as: 'followings'
    get 'followers' => 'relationships#followers', as: 'followers'
  end
    
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  
  has_one_attached :image
  belongs_to :user
  has_many :favorites, dependent: :destroy
  has_many :book_comments,dependent: :destroy
  
  validates :title,presence:true
  validates :body,presence:true,length:{maximum:200}
  
  def favorited_by?(user)
    favorites.exists?(user_id: user.id)
  end
  
  def self.search(how,value)
    if how == "0"
        @books =Book.where("title LIKE ?", "#{value}")
    elsif how == "1"
        @books =Book.where("title LIKE ?", "#{value}%")
    elsif how == "2"
        @books =Book.where("title LIKE ?", "%#{value}")
    else
        @books = Book.where(['title LIKE ?', "%#{value}%"])
    end
  end

end

app/models/book_comment.rb
class BookComment < ApplicationRecord
  belongs_to :user
  belongs_to :book
end

app/models/favorite.rb
class Favorite < ApplicationRecord
   belongs_to :user
   belongs_to :book
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books
  has_one_attached :profile_image
  has_many :favorites, dependent: :destroy
  has_many :book_comments,dependent: :destroy
  has_many :relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :reverse_of_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  
  has_many :followings, through: :relationships, source: :followed
  has_many :followers, through: :reverse_of_relationships, source: :follower
  
  validates :name, length: { minimum: 2, maximum: 20 }, uniqueness: true
  validates :introduction,length: { maximum: 50 }
  
  
  def get_profile_image
    (profile_image.attached?) ? profile_image : 'no_image.jpg'
  end
  
  def follow(user_id)
    relationships.create(followed_id: user_id)
  end

  def unfollow(user_id)
    relationships.find_by(followed_id: user_id).destroy
  end

  def following?(user)
    followings.include?(user)
  end
  
  def self.search(how,value)
    if how == "0"
      @users =User.where("name LIKE ?", "#{value}")
    elsif how == "1"
      @users =User.where("name LIKE ?", "#{value}%")
    elsif how == "2"
      @users =User.where("name LIKE ?", "%#{value}")
    else
      @users = User.where(['name LIKE ?', "%#{value}%"])
    end
  end
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!, except: [:top, :about]
  before_action :configure_permitted_parameters, if: :devise_controller?

  private

  def after_sign_in_path_for(resource)
    user_path(resource)
  end

  def after_sign_out_path_for(resource)
    root_path
  end

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email])
  end
end

app/controllers/book_comments_controller.rb
class BookCommentsController < ApplicationController
   def create
    book = Book.find(params[:book_id])
    comment = current_user.book_comments.new(book_comment_params)
    comment.book_id = book.id
    comment.save
    redirect_to book_path(book)
   end
   
    def destroy
      BookComment.find(params[:id]).destroy
      redirect_to book_path(params[:book_id])
    end
  
  private

  def book_comment_params
    params.require(:book_comment).permit(:comment)
  end

end

app/controllers/books_controller.rb
class BooksController < ApplicationController
 before_action :ensure_correct_user, only: [:edit, :update, :destroy]
  def show
    @book_1 = Book.find(params[:id])
    @user = @book_1.user
    @book = Book.new
    @book_comment = BookComment.new
  end

  def index
    @book =Book.new
    @books = Book.all
  end

  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
       flash[:notice] = "You have created book successfully."
       redirect_to book_path(@book.id)
    else
      @user = current_user
      @books = Book.all
      render :index
    end
  end

  def edit
    @book = Book.find(params[:id])
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
       book = Book.new
       book.save
       redirect_to book_path(@book), notice: "You have updated book successfully."
    else
      render "edit"
    end
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to books_path
  end

  private

   def book_params
    params.require(:book).permit(:title, :body)
   end
   
    def ensure_correct_user
      @book = Book.find(params[:id])
     unless @book.user == current_user
        redirect_to books_path
     end
    end
   
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  def create
    @book = Book.find(params[:book_id])
    favorite = current_user.favorites.new(book_id: @book.id)
    favorite.save
    # redirect_to books_path
  end
   
  def destroy
    @book = Book.find(params[:book_id])
    favorite = current_user.favorites.find_by(book_id: @book.id)
    favorite.destroy
    # redirect_to books_path
  end

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
  
  def about
  end
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController
  def create
    current_user.follow(params[:user_id])
    redirect_to request.referer
  end
  
  def destroy
    current_user.unfollow(params[:user_id])
    redirect_to request.referer  
  end
  
  def followings
    user = User.find(params[:user_id])
    @users = user.followings
  end

  def followers
    user = User.find(params[:user_id])
    @users = user.followers
  end
end

app/controllers/searchs_controller.rb
class SearchsController < ApplicationController
 def top
    if params[:search].present?
        if params[:model] == "user"
          @users =User.search(params[:how],params[:search])
        elsif params[:model] == "book"
          @books =Book.search(params[:how],params[:search])
        end
    end
 end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :ensure_correct_user, only: [:edit, :update]

  def show
    @user = User.find(params[:id])
    @books = @user.books
    @book = Book.new
  end

  def index
    @users = User.all
    @book = Book.new
  end
 
  def edit
     @user = User.find(params[:id])
  end

  def update
    if @user.update(user_params)
      flash[:notice] = "You have updated user successfully."
      user = User.new
      user.save
      redirect_to user_path(@user.id)
    else
     render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :introduction, :profile_image)
  end

  def ensure_correct_user
    @user = User.find(params[:id])
    unless @user == current_user
      redirect_to user_path(current_user)
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/book_comments_helper.rb
module BookCommentsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/searchs_helper.rb
module SearchsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_form.html.erb
<%= form_with model:book,local:true do |f| %>
  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, class: 'form-control book_title' %>
  </div>
  <div class="form-group">
    <%= f.label :opinion %>
    <%= f.text_area :body, class: 'form-control book_body' %>
  </div>
  <div class="form-group">
    <%= f.submit class: 'btn btn-success' %>
  </div>
<% end %>

app/views/books/_index.html.erb
<table class='table table-hover table-inverse'>
  <thead>
    <tr>
      <th></th>
      <th>Title</th>
      <th>Opinion</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% books.each do |book| %>
      <tr>
        <td>
          <%= link_to user_path(book.user) do %>
           <%= image_tag book.user.get_profile_image, size:'50x50' %>
          <% end %>
        </td>
        <td><%= link_to book.title,book %></td>
        <td><%= book.body %></td>
        <td class ="favorite-btn-<%= book.id %>">
          <%= render 'favorites/favorite-btn', book: book %>
        </td>
        <td>
           <%= link_to "コメント数:#{book.book_comments.count}", book_path(book.id) %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/books/edit.html.erb
<div class='container'>
   <% if @book.errors.any? %>
  <%= @book.errors.count %>errors prohibited this obj from being saved:
  <ul>
    <% @book.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>
  <div class='row'>
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
  		<h1>Editing Book</h1>
  		<%= render 'form', book: @book %>
  		<%= link_to 'Show', @book %> |
  		<%= link_to 'Back', books_path, class: "back" %>
  </div>
</div>

app/views/books/index.html.erb
<div class='container px-5 px-sm-0'>
  <% if @book.errors.any? %>
    <%= @book.errors.count %>errors prohibited this obj from being saved:
    <ul>
    <% @book.errors.full_messages.each do |message| %>
      <li><%= message %></li>
     <% end %>
    </ul>
   <% end %>
   <%= form_with(url: search_path,method: :get,local: true) do |f| %>
    <%= f.text_field :search %>
    <%= f.select :model , options_for_select({User: :user,Book: :book })%>
    <%= f.select :how , options_for_select({完全一致: :"0",前方一致: :"1",後方一致: :"2",部分一致: :"3" })%>
    <%= f.submit '検索'%>
   <% end %>
  <div class='row'>
    <div class='col-md-3'>
      <h2>User info</h2>
      <%= render 'users/info', user: current_user %>
      <h2 class="mt-3">New book</h2>
      <%= render 'form', book: @book %>
    </div>
    <div class='col-md-8 offset-md-1'>
      <h2>Books</h2>
      <%= render 'index', books: @books%>
    </div>
  </div>
</div>

app/views/books/show.html.erb
<div class='container'>
  <div class='row'>
    <div class='col-md-3'>
      <h2>User info</h2>
      <%= render 'users/info',user: @user %>
      <h2 class="mt-3">New book</h2>
      <%= render 'form', book: @book %>
    </div>
    <div class='col-md-8 offset-md-1'>
  		<h2>Book detail</h2>
  		<table class='table'>
  		  <tr>
          <td><%= link_to user_path(@book_1.user) do %>
            <%= image_tag @user.get_profile_image, size:"100x100" %><br>
            <%= @book_1.user.name %>
            <% end %>
          </td>
          <td><%= link_to @book_1.title, @book_1 %></td>
          <td><%= @book_1.body %></td>
          <td class ="favorite-btn-<%= @book_1.id %>"><%= render 'favorites/favorite-btn', book: @book_1 %></td>
          <td> <%= "コメント数:#{@book_1.book_comments.count}" %></td>
            <td>
               <% if @user == current_user %>
                <%= link_to 'Edit', edit_book_path(@book_1), class: "btn btn-sm btn-success" %></td>
               <% end %>
            <td>
              <% if @user == current_user %>
               <%= link_to 'Destroy', @book_1, method: :delete, data: { confirm: '本当に消しますか？' }, class: "btn btn-sm btn-danger"%></td>
              <% end %>
        </tr>
       </table>
        <table>
          <tr>
            <td>
               <% @book_1.book_comments.each do |book_comment| %>
               <%= image_tag @user.get_profile_image, size:"100x100" %>
               <%= book_comment.comment %>
              <% if book_comment.user == current_user %>
               <%= link_to "destroy",  book_book_comment_path(book_comment.book, book_comment), method: :delete, class: "btn btn-sm btn-danger" %>
              <% end %>
              </br>
              <%=link_to book_comment.user.name,user_path(book_comment.user) %>
           </td>
           <% end %>
          </tr>
        </table>
              <%= form_with model: [@book_1, @book_comment], local: false  do |f| %>
              <%= f.text_area :comment, rows: '5', class: "form-control"  %>
              <%= f.submit "送信" %>
              <% end %>
    </div>
  </div>
</div>

app/views/favorites/_favorite-btn.html.erb
  
  <% if book.favorited_by?(current_user) %>
         <%= link_to book_favorites_path(book), method: :delete, remote: true do %>
          ♥<%= book.favorites.count %> 
    　    <% end %>
        <% else %>
        <%= link_to book_favorites_path(book), method: :post, remote: true do %>
         ♡<%= book.favorites.count %> 
        <% end %>
　<% end %>

app/views/favorites/create.js.erb
 $(".favorite-btn").html("<%= j(render 'favorites/favorite-btn', book: @book) %>");

app/views/favorites/destroy.js.erb
 $(".favorite-btn-<%= @book.id %>").html("<%= j(render 'favorites/favorite-btn', book: @book) %>");

app/views/homes/about.html.erb
<div class='container'>
  <div class='row'>
    <h1 class="px-3 mx-auto">Welcome to <i class="fas fa-book"></i><strong>Bookers</strong>!</h1>
  </div>
</div>

app/views/homes/top.html.erb
<div class="container">
  <div class="row">
    <div class='mx-auto col-11 col-sm-10 col-lg-8 col-xl-6'>
      <h1>welcome to <i class="fas fa-book"></i><strong>Bookers</strong>  !!</h1>
      <p>In  <i class="fas fa-book"></i><strong>Bookers</strong>, </p>
      <p>you can share and exchange  your opinions , inpressions , and emotions</p>
      <p> about various books!</p>
      <div class="btn-wrapper col-10 mx-auto">
        <div class="row">
          <%= link_to 'Log in',new_user_session_path, class: "btn btn-info btn-sm btn-block mb-3 sign_in" %>
        </div>
        <div class="row">
          <%= link_to 'Sign up',new_user_registration_path, class: "btn btn-success btn-sm btn-block sign_up" %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/relationships/_follow_list.html.erb
<% if @users.exists? %>
  <% @users.each do |user| %>
    <table>
      <thead>
        <tr>
          <th>name</th>
          <th></th>
          <th></th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <td><%= user.name %></td>
          <td>フォロー数:<%= user.followings.count %></td>
          <td>フォロワー数: <%= user.followers.count %></td>
        </tr>
      </tbody>
    </table>
  <% end %>
<% else %>
  <p>ユーザーはいません</p>
<% end %>

app/views/relationships/followers.html.erb
<% if @users.exists? %>
  <% @users.each do |user| %>
    <table>
      <thead>
        <tr>
          <th>image</th>
          <th>name</th>
          <th></th>
          <th></th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <td><%= image_tag user.get_profile_image, size: '100x100' %></td>
          <td><%= user.name %></td>
          <td>フォロー数:<%= user.followings.count %></td>
          <td>フォロワー数: <%= user.followers.count %></td>
        </tr>
      </tbody>
    </table>
  <% end %>
<% else %>
  <p>ユーザーはいません</p>
<% end %>

app/views/relationships/followings.html.erb
<% if @users.exists? %>
  <% @users.each do |user| %>
    <table>
      <thead>
        <tr>
          <th>image</th>
          <th>name</th>
          <th></th>
          <th></th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <td><%= image_tag user.get_profile_image, size: '100x100' %></td>
          <td><%= user.name %></td>
          <td>フォロー数:<%= user.followings.count %></td>
          <td>フォロワー数: <%= user.followers.count %></td>
        </tr>
      </tbody>
    </table>
  <% end %>
<% else %>
  <p>ユーザーはいません</p>
<% end %>

app/views/searchs/top.html.erb
   <% if params[:search].present? %>
     <% if params[:model] == "user" %>
      <% @users.each do |f| %>
        <div class="col-md-8 offset-md-1">
         <h2>User</h2>
         <table class="table">
          <thead>
            <tr>
              <th>image</th>
              <th>name</th>
              <th></th>
              <th colspan="3"></th>
            </tr>
          </thead>
          <tbody>
            <tr>
             <td><%= image_tag f.get_profile_image, size: '100x100' %></td>
             <td><%= f.name %></td>
             <td></td>
            </tr>
          </tbody>
         </table>
        <% end %>
    </div>
   <div class="row">
       <% elsif params[:model] == "book"%>
         <div class="col-md-8 offset-md-1">
           <h2>Book</h2>
             <% @books.each do |f| %>
               <table class="table">
                <thead>
                  <tr>
                    <th></th>
                    <th>title</th>
                    <th>opinion</th>
                    <th colspan="3"></th>
                  </tr>
                </thead>
                <tbody>
                  <tr>
                    <td><%= image_tag f.user.get_profile_image, size: '100x100' %></td>
                    <td><%= f.title %></td>
                    <td><%= f.body %></td>
                    <td></td>
                    </tr>
                </tbody>
               </table>
             <% end %>
           </div>
        </div>
        <% end %>
   
<% else %>
<h1>検索結果は存在しません</h1>
<% end %>

app/views/users/_index.html.erb
<table class='table'>
  <thead>
    <tr>
      <th>image</th>
      <th>name</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% users.each do |user| %>
      <tr>
        <td><%= image_tag user.get_profile_image, size: '100x100' %></td>
        <td><%= user.name %></td>
        <td>
          フォロー数: <%= user.followings.count %>
        </td>
        <td>
          フォロワー数: <%= user.followers.count %>
        </td>
        <td>
          <% unless current_user == user %>
          <% if current_user.following?(user) %>
          <%= link_to "フォロー外す", user_relationships_path(user.id), method: :delete %>
         <% else %>
         <%= link_to "フォローする", user_relationships_path(user.id), method: :post %>
         <% end %>
         <% end %>
  　   　</td>
        <td><%= link_to 'Show', user %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/users/_info.html.erb
<table class='table'>
  <tr><%= image_tag user.get_profile_image, size:'100x100' %></tr>
  <tr>
	  <th>name</th>
	  <th><%= user.name %></th>
  </tr>
  <tr>
	  <th>introduction</th>
	  <th><%= user.introduction %></th>
  </tr>
  <tr>
    <th>follows</th>
    <th><%= link_to user.followings.count, user_followings_path(user) %></th>
  </tr>
    <th>followers</th>
    <th> <%= link_to user.followers.count, user_followers_path(user) %></th>
    <tr>
      <th>
      <% unless current_user == user %>
       <% if current_user.following?(user) %>
          <%= link_to "フォロー外す", user_relationships_path(user.id), method: :delete, class: "btn btn-sm btn-danger" %>
        <% else %>
         <%= link_to "フォローする", user_relationships_path(user.id), method: :post, class: "btn btn-sm btn-success" %>
       <% end %>
      <% end %>
      </th>
   </tr>
</table>
　
<div class='row'>
  <%= link_to edit_user_path(user), class: "btn btn-outline-secondary btn-block" do %>
    <i class="fas fa-user-cog"></i>
  <% end %>
</div>

app/views/users/edit.html.erb
<div class='container'>
  <div class='row'>
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
    <h2>User info</h2>
    <%= form_with model:@user, local:true do |f| %>
      <%= render 'layouts/errors', obj: @user %>
      <div class="form-group">
        <%= f.label :name %>
        <%= f.text_field :name, class: "form-control name" %>
      </div>
     <div class="form-group">
        <%= f.label :image %>
        <%= f.file_field :profile_image, class: "form-control-file user_image", accept: 'image/*' %>
      </div>
      <div class="form-group">
        <%= f.label :introduction %>
        <%= f.text_area :introduction, class: "form-control introduction" %>
      </div>
      <div class="form-group">
        <%= f.submit class: 'btn btn-secondary' %>
      </div>
    <% end %>
  </div>
</div>

app/views/users/index.html.erb
  <p id="notice"></p>
  <div class="container px-5 px-sm-0">
   <div class="row">
    <div class="col-md-3">
      <h2>User info</h2>
      <%= render 'info', user: current_user %>
      <h2 class="mt-3">New book</h2>
      <%= render 'books/form', book: @book %>
    </div>
     <div class="col-md-8 offset-md-1">
      <h2>Users</h2>
      <%= render 'index',users: @users %>
     </div>
   </div>
  </div>

app/views/users/show.html.erb
<div class='container px-5 px-sm-0'>
  <div class='row'>
    <div class='col-md-3'>
      <h2>User info</h2>
      <%= render 'info', user: @user %>
      <h2 class="mt-3">New book</h2>
      <%= render 'books/form', book: @book %>
    </div>
    <div class='col-md-8 offset-md-1'>
      <h2>Books</h2>
      <%= render 'books/index',books: @books %>
    </div>
  </div>
</div>